### Get student
GET http://localhost:8080/students/1

### Get students
GET http://localhost:8080/students?size=10&page=0

### Create student
POST http://localhost:8080/students
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john@doe.com"
}

### Update student
PUT http://localhost:8080/students/1
Content-Type: application/json

{
"firstName": "Updated",
"lastName": "User",
"email": "updated@mail.com"
}

### Delete student
DELETE http://localhost:8080/students/1

### Get courses
GET http://localhost:8080/courses

### Get course by id
GET http://localhost:8080/courses/1

### Create course
POST http://localhost:8080/courses
Content-Type: application/json

{
  "title": "Art et dessin",
  "description": "Nous allons beaucoup dessiner",
  "courseType": "ART",
  "teacherId": null
}

### Update course
PUT http://localhost:8080/courses/1
Content-Type: application/json

{
  "title": "Advanced Math",
  "description": "Advanced algebra",
  "courseType": "COMPUTER_SCIENCE",
  "teacherId": 0
}

### Delete course
DELETE http://localhost:8080/courses/1

### Enroll student
POST http://localhost:8080/enrollments
Content-Type: application/json

{
  "studentId": 1,
  "courseId": 1,
  "type": "NORMAL"
}

### Delete enrollment
DELETE http://localhost:8080/enrollments/1